rootProject.name = "data-module"
include("api")
include("common-sql")
include("mysql-module")
include("sqlite-module")
include("json-module")
include("mongodb-module")
include("universal-module")
include("testing")
include("postgresql-module")
include("h2-module")
include("property-module")
